### ISSUE TITLE
Problem getting encrypted file to upload

### ISSUE THREAD

**Issue by jclev** [kothar/go-backblaze#13]
Good afternoon,  I am trying to encrypt a file using the encryption example here https://golang.org/pkg/crypto/cipher/#NewOFB and then upload it using your B2 library.
The problem is I can't seem to get a way to pass the output of the cipher.StreamWriter to UploadFile I have tried to use os.pipe but have not bin able to get it to work. I know this isn't a problem with you library but since I'm sure you know much more about this then me I was wondering if you could help me out here is the code i have bin working on but it doesn't work. I could create a none working example and post it to my GitHub if you like. 

`func (b2h *B2Handler) EncyptandUpload(iv []byte, fileName string, outputFileName string) {
	key := []byte("example key 1234")

	inFile, err := os.Open(fileName)
	if err != nil {
		panic(err)
	}
	defer inFile.Close()

	block, err := aes.NewCipher(key)
	if err != nil {
		panic(err)
	}

	stream := cipher.NewOFB(block, iv[:])

	outFile, err := os.OpenFile(outputFileName, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		panic(err)
	}
	defer outFile.Close()
	
	
	writer := &cipher.StreamWriter{S: stream, W: w}
	// Copy the input file to the output file, encrypting as we go.
	if _, err := io.Copy(writer, inFile); err != nil {
		panic(err)
	}

	
	metadata := make(map[string]string)
       //just the current selected bucket
	_, err3 := b2h.currentBucket.UploadFile(outputFileName, metadata, write)

	if err3 != nil {
		fmt.Println(err3.Error)
	}
}`

**Comment by kothar** [comment]
Hi jclev,

I've seen some replies in the golang-nuts mailing list already, but to add to those comments:

1. Do you want to save the file to disk at the same time as uploading it (outFile) or is that just a temporary workaround?
In order to upload to B2 the hash of the file needs to be known in advance, so the B2 library will attempt to calculate this first: https://github.com/kothar/go-backblaze/blob/master/files.go#L43
This means that uploading an encrypted stream directly will actually buffer the whole encrypted file before it uploads it, as the stream will not allow seeking in the same way as a file would.
I suggest you write the encrypted file to disk first and then upload it if the file is likely to be larger than a few megabytes.
2. If you do want to stream the encrypted file without saving it to disk, you need to construct a new io.Reader which pulls data from an io.Writer. io.Pipe will create a pair like this, but you may have confused this with os.Pipe. See https://golang.org/pkg/io/#Pipe for the correct method.
As Uvelichitel mentioned on the mailing list, you need two go routines: one to push data into the writer and one to read it from the reader.
I suggest the following:

```
pipeReader, pipeWriter := io.Pipe()
writer := &cipher.StreamWriter{S: stream, W: pipeWriter}

// Do the encryption in a goroutine
go func() {
    io.Copy(writer, inFile)
    // Errors should be checked
    writer.Close()
}()

// Upload to B2 in the main routine
b2h.currentBucket.UploadFile(outputFileName, metadata, pipeReader)
// Errors should be checked
```

3. The io.TeeReader will handle the case where you want to write to both the file and upload at the same time, but as mentioned before, the B2 library will buffer this in memory to compute the hash, so it would be better to save to the file first, then upload the file.
4. The bytes.Buffer method is essentially what the B2 library does internally, so you won't gain anything in memory usage, but it does make the logic of the program more obvious since it doesn't require an extra goroutine.

I hope that helps!

**Comment by kothar** [comment]
Regarding your code above, I think there are two reasons it doesn't work:

1. `writer := &cipher.StreamWriter{S: stream, W: w}` should use `outFile` instead of `w`
2. after `io.copy`, you need to close `outFile` and reopen it for reading: you will need to remove the `defer outFile.Close()` and then explicitly `os.Open(outputFileName)` to get a new reader.
Alternatively, you could open `outFile` with the `O_RDWR` mode, which would then allow you to reset the position in the file to the beginning and use it as a reader directly:
```
outFile.Seek(0,0)
b2h.currentBucket.UploadFile(outputFileName, metadata, outFile)
```

**Comment by jclev** [comment]
Thank you for your reply! I was thinking it was better to have it go from unencrypted file -> encryption function -> upload function with out creating a temporary file but after reading your reply it really should go to a temp file before uploaded. It seemed like i was missing someway of getting the date passed to the upload function without creating the temp file and the fact is that isn't the correct way to upload it. 
I thought creating the temp file would just consume disk space with out giving any benefits.

**Comment by kothar** [comment]
Hi again,

Just had a thought: while you're writing the file to disk it would save you one pass through the file if you also compute the SHA1 hash of the data as you write it (after encryption).

You can then pass a new file reader in to the `UploadHashedFile` method:
https://github.com/kothar/go-backblaze/blob/master/files.go#L85

This will avoid the `UploadFile` method needing to read the whole file first to compute the hash, and then reading it a second time for upload.

To do this you may want to use the `TeeWriter` method previously discussed.

You mention that you need a temp file to use the library correctly, but in fact you could still use a `bytes.Buffer` object for an in-memory buffer of the encrypted data, it wouldn't behave any differently to the temp file, but does need to fit the whole thing in memory, since it can't start the upload until the whole file is hashed. Sorry if I implied that you needed to use a temp file - I just mean that you need to buffer it somewhere.

If the file will fit in memory, I recommend just streaming it to the `UploadFile` method using the `io.Pipe` method, and skipping the temp file. This will buffer the data, compute the SHA1, and then upload the data for you.

**Comment by jclev** [comment]
For the life of me I can not get this to work without a temp file. It always "blocks" on UploadFile  and just runs for ever. 

```
//EncyptandUpload encypt a file and upload it to B2Handler.currentBucket
func (b2h *B2Handler) EncyptandUpload(iv []byte, fileName string, outputFileName string) {
	key := []byte("example key 1234")

	inFile, err := os.Open(fileName)
	if err != nil {
		panic(err)
	}
	defer inFile.Close()

	block, err := aes.NewCipher(key)
	if err != nil {
		panic(err)
	}

	stream := cipher.NewOFB(block, iv[:])

	pReader, pWriter := io.Pipe()
	writer := &cipher.StreamWriter{S: stream, W: pWriter}

	go re(writer, inFile) 

	metadata := make(map[string]string)
	//upload file

	_, err3 := b2h.currentBucket.UploadFile(outputFileName, metadata, pReader)
	if err3 != nil {
		log.Fatal(err3.Error)
	}

}

func re(dst io.Writer, src io.Reader) {
	fmt.Println(1)
	_, err := io.Copy(dst, src)
	if err != nil {
		println(err)
	}
	fmt.Println(2)
}
```
It is almost like the something is out of sync or they can't work at the same time? It feels so simple that it is bugging me that everyone else seems to be getting it and I'm missing something. 
Also I can't find a TeeWriter method in any of the general libraries am I missing it?
Thank you for your help!

**Comment by kothar** [comment]
Hi, the reason it's hanging is that you're not closing your `StreamWriter` after the `io.Copy`, which means the `UploadFile` method thinks it's still waiting for more data. Here's a slight modification to your `re` function which solves that problem. Note that you need to declare `dst` as a `*StreamWriter` so that you can access the `Close()` method. You could also make it an `io.CloseWriter` with the same effect.

``` go
func re(dst *cipher.StreamWriter, src io.Reader) {
	fmt.Println(1)
	_, err := io.Copy(dst, src)
	if err != nil {
		println(err)
	}
	fmt.Println(2)
	dst.Close()
}
```

There's no `TeeWriter` as far as I can see, only `TeeReader`, but I think it does what you want in this case: https://golang.org/pkg/io/#TeeReader

You could use this just before the call to `UploadFile` to send the output somewhere else as it's uploaded:

``` go
	tReader := io.TeeReader(pReader, os.Stdout)
	_, err3 := b2h.currentBucket.UploadFile(outputFileName, metadata, tReader)
```

Hope that gets you unstuck!

Mike.

**Comment by jclev** [comment]
That was what was getting me stuck. Now uploading is working without a temp file. I'm going to have to play with the TeeReader to understand how that would work and if it would work better. Thank you for all your help! I am learning a lot with this project.
