### ISSUE TITLE
Unable to install b2

### ISSUE THREAD

**Issue by prologic** [kothar/go-backblaze#14]
```#!bash
$ go install gopkg.in/kothar/go-backblaze.v0/b2
can't load package: package gopkg.in/kothar/go-backblaze.v0/b2: cannot find package "gopkg.in/kothar/go-backblaze.v0/b2" in any of:
	/usr/local/Cellar/go/1.9/libexec/src/gopkg.in/kothar/go-backblaze.v0/b2 (from $GOROOT)
	/Users/prologic/go/src/gopkg.in/kothar/go-backblaze.v0/b2 (from $GOPATH)
```

**Comment by kothar** [comment]
Hi, that's an error in the README which is now fixed.

Use `go get -u gopkg.in/kothar/go-backblaze.v0/b2` instead, since `go install` will only work if you have already cloned the repo into your GOPATH, hence the error about not being able to find the package.

Thanks for the report! Sorry I didn't consider this before.

**Comment by prologic** [comment]
Thanks!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
