### ISSUE TITLE
Support copy file

### ISSUE THREAD

**Issue by ghost** [kothar/go-backblaze#34]
Backblaze now has support for copying files without downloading the source. Any chance that it can be added? https://www.backblaze.com/blog/backblaze-b2-copy-file-beta-is-now-public/

**Comment by kothar** [comment]
That's excellent news - I remember talking to someone from Backblaze about this several years ago, and sounds like many other people had the same request.

I've not been actively working with this library for a while, but I will try to spend some time with it over Christmas - in the meantime I would happily accept a patch from anyone who feels like adding this API method. (if anyone does pick it up, please comment here first so that we can coordinate)

**Comment by kothar** [comment]
Sorry it's taken a year, but thanks to @denis-tkachuk the support for this API method has been added in #38.
